/**
 * ATS production safety boundary.
 *
 * Small, explicit guards around the things that can hurt a live server: a
 * parser that never returns, a filename from a stranger, an id from a URL, and
 * a deployment that silently persists to a local file instead of a database.
 * None of these change how the ATS scores anything — they decide whether a
 * request is allowed to reach the scorer at all.
 */

/** Parsing a document is the only unbounded work in the ATS request path. */
export const PARSE_TIMEOUT_MS = 20_000;

export class AtsTimeoutError extends Error {
  constructor() { super('ATS_PARSE_TIMEOUT'); this.name = 'AtsTimeoutError'; }
}

/**
 * Bound how long a parse may take.
 *
 * lib/server/document-parser.ts shells out to pdftotext / pdftoppm through
 * execFile with NO timeout, so a malformed or adversarial PDF can hold a
 * request open indefinitely. This does not kill that child process — only the
 * parser itself could do that, and rewriting it is out of scope — but it stops
 * one bad document from pinning a request handler forever. The honest
 * description is a REQUEST bound, not a process bound.
 */
export async function withParseTimeout<T>(work: Promise<T>, ms = PARSE_TIMEOUT_MS): Promise<T> {
  let timer: NodeJS.Timeout | undefined;
  try {
    return await Promise.race([
      work,
      new Promise<never>((_resolve, reject) => {
        timer = setTimeout(() => reject(new AtsTimeoutError()), ms);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

/**
 * A filename safe to store, log and display.
 *
 * The parser itself is not vulnerable to traversal — it writes to fixed names
 * (`source.pdf`) inside an mkdtemp directory, and its extension helper reads
 * only the text after the LAST dot, which therefore can never contain a path
 * separator or `..`. This is defence in depth for the OTHER two places the name
 * travels: a stored history record and a log line. Directory components are
 * dropped rather than escaped, so "../../etc/passwd" becomes "passwd".
 */
export function safeFileName(raw: unknown): string {
  if (typeof raw !== 'string') return 'resume';
  const base = raw.split(/[\\/]/).pop() ?? '';
  const cleaned = base
    // eslint-disable-next-line no-control-regex
    .replace(/[\u0000-\u001f\u007f]/g, '')   // control characters, including NUL
    .replace(/^\.+/, '')                     // no leading dots: "..", ".env"
    .trim()
    .slice(0, 120);
  return cleaned || 'resume';
}

/**
 * Report ids are generated by crypto.randomUUID, so anything that is not a UUID
 * did not come from this system. Rejecting the shape before the query keeps
 * arbitrary caller-controlled values out of the database entirely.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidReportId(id: unknown): id is string {
  return typeof id === 'string' && UUID_RE.test(id);
}

/**
 * Whether the JSON file fallback is acceptable here.
 *
 * The fallback exists so a developer with no MONGODB_URI can run the app. In
 * production it would be a silent trap: on a serverless or multi-instance
 * deploy each instance would keep its own file, history would appear and
 * vanish depending on which instance served the request, and nothing would
 * report an error. Production therefore REQUIRES a real database, and a missing
 * one fails loudly rather than degrading into local storage.
 */
export function isProduction(): boolean {
  return process.env.NODE_ENV === 'production';
}

export class AtsStorageUnavailableError extends Error {
  constructor() {
    super('ATS_STORAGE_UNAVAILABLE');
    this.name = 'AtsStorageUnavailableError';
  }
}

/** Throws in production when no database is configured. No-op in development. */
export function assertPersistenceAvailable(hasDatabase: boolean): void {
  if (!hasDatabase && isProduction()) throw new AtsStorageUnavailableError();
}

/* ── Structured logging ───────────────────────────────────────────────────
   One line per ATS event, matching the project's existing console-based
   logging (see app/api/profile/upload-resume/route.ts). METADATA ONLY: never a
   resume, never a job description, never a document's contents — sizes,
   durations and outcomes, which is what an operator needs and what a support
   ticket can safely quote. */

export type AtsLogEvent =
  | 'ATS_EVALUATION_STARTED'
  | 'ATS_EVALUATION_COMPLETED'
  | 'ATS_EVALUATION_FAILED'
  | 'ATS_UPLOAD_COMPLETED'
  | 'ATS_UPLOAD_FAILED'
  | 'ATS_RATE_LIMITED'
  | 'ATS_HISTORY_WRITE_FAILED'
  | 'ATS_STORAGE_UNAVAILABLE';

/**
 * A stable, non-reversible reference to a user, for log correlation.
 *
 * The raw id is a durable account identifier that would then sit in log
 * aggregation forever; a short hash correlates one user's requests to each
 * other without putting that identifier in every line.
 */
export function logUserRef(userId: string): string {
  let hash = 0;
  for (let i = 0; i < userId.length; i += 1) {
    hash = ((hash << 5) - hash + userId.charCodeAt(i)) | 0;
  }
  return `u_${(hash >>> 0).toString(36)}`;
}

export function atsLog(
  event: AtsLogEvent,
  fields: Record<string, string | number | boolean | undefined>,
): void {
  const parts = Object.entries(fields)
    .filter(([, value]) => value !== undefined)
    .map(([key, value]) => `${key}=${typeof value === 'string' ? JSON.stringify(value) : value}`);
  const line = `[ats] ${event} ${parts.join(' ')}`;
  if (event.endsWith('_FAILED') || event === 'ATS_STORAGE_UNAVAILABLE') console.error(line);
  else console.log(line);
}
