/**
 * The sidebar, in the language the person actually thinks in.
 *
 * ═══ WHAT IS AND IS NOT TRANSLATED ═══
 *
 * Two different things wear the word "multilingual" here, and only one of them
 * lives in this file.
 *
 *   THE FORM'S language is handled on the server, in lib/apply/i18n-labels.ts.
 *   A label reading "पहला नाम" has to become `firstName` before anything can be
 *   written into it, and that is a matching problem, not a presentation one.
 *
 *   THE SIDEBAR'S language is this file. The questions we ask, the buttons, the
 *   warnings — the half of the conversation that is ours.
 *
 * The employer's own wording is NEVER translated. It is shown underneath our
 * question, verbatim, in whatever language the form is in: it is the thing that
 * is actually being answered, and a machine translation of a legal question
 * about visa status is not something to put in front of someone as if it were
 * what the employer asked.
 *
 * ═══ THE PROMPTS ARE KEYED, NOT MATCHED ═══
 *
 * A question carries a signature like `key:workAuthorization`. That key is what
 * PROMPTS is indexed by, so a curated translation is possible for the questions
 * in our taxonomy however the employer worded theirs. A question we could not
 * classify has signature `q:<their words>` and is shown in their words — the
 * honest outcome, and visibly so.
 *
 * Anything missing in a language falls back to English rather than to a blank.
 */

(() => {
  /* ── Chrome ─────────────────────────────────────────────────────────── */

  const UI = {
    en: {
      ready: 'ready', filling: 'filling…', done: 'done', left: '{n} left',
      idleH: 'Auto-fill this application',
      idleP: '{n} fields found. They fill from your Docrud profile, and you check everything before anything is sent.',
      fill: 'Fill this application',
      stepScan: 'Reading the form', stepMap: 'Matching against your profile',
      stepWrite: 'Writing your answers', stepFill: 'Filling the form',
      confTitle: 'Confidence', filledOf: '{a} / {b} fields filled',
      subReview: 'Check before you send', subFilled: 'Filled', subLeft: 'Left for you',
      ctaQuestions: 'Answer {n} quick questions', ctaQuestion: 'Answer 1 quick question',
      ctaSubmit: 'Review and submit',
      editH: 'Edit this answer', save: 'Save', cancel: 'Cancel', edit: 'Edit',
      suggestions: 'Other answers that fit', looksRight: 'Looks right', checked: 'Checked',
      askN: 'Question {i} of {n}', askSrc: 'the form calls this “{x}”',
      askPlaceholder: 'Type your answer…', askSend: 'Save and continue', askSkip: 'Skip this one',
      recall: 'Last time you said {x}', fromProfile: 'from your profile',
      chatMore: '{n} more fields filled',
      savedProfile: 'Saved to your profile — the next form that asks these fills itself.',
      submitH: 'Ready to submit?', submitFix: 'Fix these first',
      submitWarn: 'This presses the employer’s own submit button. It cannot be undone.',
      submitGo: 'Submit application', submitting: 'Submitting…', submitted: 'Application sent',
      errNoFields: 'No form fields on this page.',
      langLabel: 'Language', nothingSubmitted: 'Nothing is sent until you press submit here.',
      reqEmpty: 'required, still empty',
      addProfile: 'Add {x} to your Docrud profile and more of this fills itself next time.',
      youEdited: 'you edited this',
      submitFailed: 'The submit button could not be pressed.',
      back: 'Back', frameNote: 'in an embedded form',
    },
    hi: {
      ready: 'तैयार', filling: 'भरा जा रहा है…', done: 'पूरा', left: '{n} बाकी',
      idleH: 'यह आवेदन अपने आप भरें',
      idleP: '{n} फ़ील्ड मिले। ये आपकी Docrud प्रोफ़ाइल से भरे जाएंगे, और भेजने से पहले आप सब कुछ जाँच सकते हैं।',
      fill: 'यह आवेदन भरें',
      stepScan: 'फ़ॉर्म पढ़ा जा रहा है', stepMap: 'आपकी प्रोफ़ाइल से मिलान',
      stepWrite: 'आपके उत्तर लिखे जा रहे हैं', stepFill: 'फ़ॉर्म भरा जा रहा है',
      confTitle: 'भरोसा', filledOf: '{b} में से {a} फ़ील्ड भरे',
      subReview: 'भेजने से पहले जाँचें', subFilled: 'भरे गए', subLeft: 'आपके लिए बाकी',
      ctaQuestions: '{n} छोटे सवालों के जवाब दें', ctaQuestion: '1 छोटे सवाल का जवाब दें',
      ctaSubmit: 'जाँचें और भेजें',
      editH: 'यह उत्तर बदलें', save: 'सहेजें', cancel: 'रद्द करें', edit: 'बदलें',
      suggestions: 'और उपयुक्त उत्तर', looksRight: 'सही है', checked: 'जाँचा गया',
      askN: '{n} में से सवाल {i}', askSrc: 'फ़ॉर्म इसे “{x}” कहता है',
      askPlaceholder: 'अपना उत्तर लिखें…', askSend: 'सहेजें और आगे बढ़ें', askSkip: 'इसे छोड़ें',
      recall: 'पिछली बार आपने कहा था {x}', fromProfile: 'आपकी प्रोफ़ाइल से',
      chatMore: '{n} और फ़ील्ड भरे गए',
      savedProfile: 'आपकी प्रोफ़ाइल में सहेजा गया — अगली बार यह सवाल अपने आप भर जाएगा।',
      submitH: 'भेजने के लिए तैयार?', submitFix: 'पहले इन्हें ठीक करें',
      submitWarn: 'इससे कंपनी का अपना सबमिट बटन दबेगा। इसे वापस नहीं लिया जा सकता।',
      submitGo: 'आवेदन भेजें', submitting: 'भेजा जा रहा है…', submitted: 'आवेदन भेज दिया गया',
      errNoFields: 'इस पेज पर कोई फ़ॉर्म फ़ील्ड नहीं मिला।',
      langLabel: 'भाषा', nothingSubmitted: 'जब तक आप यहाँ सबमिट नहीं दबाते, कुछ नहीं भेजा जाता।',
      reqEmpty: 'ज़रूरी है, अभी खाली है',
      addProfile: 'अपनी Docrud प्रोफ़ाइल में {x} जोड़ें, अगली बार यह अपने आप भर जाएगा।',
      youEdited: 'आपने इसे बदला',
      submitFailed: 'सबमिट बटन नहीं दबाया जा सका।',
      back: 'वापस', frameNote: 'एम्बेडेड फ़ॉर्म में',
    },
    bn: {
      ready: 'প্রস্তুত', filling: 'পূরণ করা হচ্ছে…', done: 'সম্পন্ন', left: '{n} বাকি',
      idleH: 'এই আবেদনটি স্বয়ংক্রিয়ভাবে পূরণ করুন',
      idleP: '{n}টি ঘর পাওয়া গেছে। এগুলি আপনার Docrud প্রোফাইল থেকে পূরণ হবে, পাঠানোর আগে আপনি সব দেখে নিতে পারবেন।',
      fill: 'এই আবেদনটি পূরণ করুন',
      stepScan: 'ফর্মটি পড়া হচ্ছে', stepMap: 'আপনার প্রোফাইলের সঙ্গে মেলানো হচ্ছে',
      stepWrite: 'আপনার উত্তর লেখা হচ্ছে', stepFill: 'ফর্ম পূরণ করা হচ্ছে',
      confTitle: 'আস্থা', filledOf: '{b}টির মধ্যে {a}টি ঘর পূরণ',
      subReview: 'পাঠানোর আগে দেখে নিন', subFilled: 'পূরণ হয়েছে', subLeft: 'আপনার জন্য বাকি',
      ctaQuestions: '{n}টি ছোট প্রশ্নের উত্তর দিন', ctaQuestion: '১টি ছোট প্রশ্নের উত্তর দিন',
      ctaSubmit: 'দেখে নিয়ে পাঠান',
      editH: 'এই উত্তরটি বদলান', save: 'সংরক্ষণ', cancel: 'বাতিল', edit: 'বদলান',
      suggestions: 'আরও মানানসই উত্তর', looksRight: 'ঠিক আছে', checked: 'দেখা হয়েছে',
      askN: '{n}টির মধ্যে প্রশ্ন {i}', askSrc: 'ফর্মে একে বলা হয়েছে “{x}”',
      askPlaceholder: 'আপনার উত্তর লিখুন…', askSend: 'সংরক্ষণ করে এগিয়ে যান', askSkip: 'এটি বাদ দিন',
      recall: 'গতবার আপনি বলেছিলেন {x}', fromProfile: 'আপনার প্রোফাইল থেকে',
      chatMore: 'আরও {n}টি ঘর পূরণ হয়েছে',
      savedProfile: 'আপনার প্রোফাইলে সংরক্ষিত — পরের ফর্মে এটি নিজেই পূরণ হবে।',
      submitH: 'পাঠাতে প্রস্তুত?', submitFix: 'আগে এগুলি ঠিক করুন',
      submitWarn: 'এটি নিয়োগকর্তার নিজস্ব সাবমিট বোতাম চাপবে। এটি ফেরানো যাবে না।',
      submitGo: 'আবেদন পাঠান', submitting: 'পাঠানো হচ্ছে…', submitted: 'আবেদন পাঠানো হয়েছে',
      errNoFields: 'এই পাতায় কোনও ফর্মের ঘর নেই।',
      langLabel: 'ভাষা', nothingSubmitted: 'আপনি এখানে সাবমিট না চাপা পর্যন্ত কিছুই পাঠানো হয় না।',
      reqEmpty: 'আবশ্যক, এখনও ফাঁকা',
      addProfile: 'আপনার Docrud প্রোফাইলে {x} যোগ করুন, পরের বার এটি নিজেই পূরণ হবে।',
      youEdited: 'আপনি এটি বদলেছেন',
      submitFailed: 'সাবমিট বোতামটি চাপা গেল না।',
      back: 'ফিরে যান', frameNote: 'একটি এমবেড করা ফর্মে',
    },
    ta: {
      ready: 'தயார்', filling: 'நிரப்பப்படுகிறது…', done: 'முடிந்தது', left: '{n} மீதம்',
      idleH: 'இந்த விண்ணப்பத்தைத் தானாக நிரப்பு',
      idleP: '{n} புலங்கள் கிடைத்தன. இவை உங்கள் Docrud சுயவிவரத்திலிருந்து நிரப்பப்படும்; அனுப்பும் முன் நீங்கள் அனைத்தையும் பார்க்கலாம்.',
      fill: 'இந்த விண்ணப்பத்தை நிரப்பு',
      stepScan: 'படிவம் படிக்கப்படுகிறது', stepMap: 'உங்கள் சுயவிவரத்துடன் பொருத்துகிறது',
      stepWrite: 'உங்கள் பதில்கள் எழுதப்படுகின்றன', stepFill: 'படிவம் நிரப்பப்படுகிறது',
      confTitle: 'நம்பகத்தன்மை', filledOf: '{b} இல் {a} புலங்கள் நிரப்பப்பட்டன',
      subReview: 'அனுப்பும் முன் சரிபார்க்கவும்', subFilled: 'நிரப்பப்பட்டது', subLeft: 'உங்களுக்காக மீதம்',
      ctaQuestions: '{n} சிறு கேள்விகளுக்குப் பதிலளிக்கவும்', ctaQuestion: '1 சிறு கேள்விக்குப் பதிலளிக்கவும்',
      ctaSubmit: 'சரிபார்த்து அனுப்பு',
      editH: 'இந்தப் பதிலை மாற்று', save: 'சேமி', cancel: 'ரத்து', edit: 'மாற்று',
      suggestions: 'பொருந்தும் மற்ற பதில்கள்', looksRight: 'சரியாக உள்ளது', checked: 'சரிபார்க்கப்பட்டது',
      askN: '{n} இல் கேள்வி {i}', askSrc: 'படிவம் இதை “{x}” என்கிறது',
      askPlaceholder: 'உங்கள் பதிலைத் தட்டச்சு செய்யவும்…', askSend: 'சேமித்து தொடரவும்', askSkip: 'இதைத் தவிர்',
      recall: 'கடந்த முறை நீங்கள் {x} என்றீர்கள்', fromProfile: 'உங்கள் சுயவிவரத்திலிருந்து',
      chatMore: 'மேலும் {n} புலங்கள் நிரப்பப்பட்டன',
      savedProfile: 'உங்கள் சுயவிவரத்தில் சேமிக்கப்பட்டது — அடுத்த படிவத்தில் இது தானே நிரம்பும்.',
      submitH: 'அனுப்பத் தயாரா?', submitFix: 'முதலில் இவற்றைச் சரிசெய்யவும்',
      submitWarn: 'இது நிறுவனத்தின் சொந்த சமர்ப்பி பொத்தானை அழுத்தும். இதைத் திரும்பப் பெற முடியாது.',
      submitGo: 'விண்ணப்பத்தை அனுப்பு', submitting: 'அனுப்பப்படுகிறது…', submitted: 'விண்ணப்பம் அனுப்பப்பட்டது',
      errNoFields: 'இந்தப் பக்கத்தில் படிவப் புலங்கள் இல்லை.',
      langLabel: 'மொழி', nothingSubmitted: 'நீங்கள் இங்கே சமர்ப்பி அழுத்தும் வரை எதுவும் அனுப்பப்படாது.',
      reqEmpty: 'அவசியம், இன்னும் காலியாக உள்ளது',
      addProfile: 'உங்கள் Docrud சுயவிவரத்தில் {x} சேர்த்தால் அடுத்த முறை இது தானே நிரம்பும்.',
      youEdited: 'இதை நீங்கள் மாற்றினீர்கள்',
      submitFailed: 'சமர்ப்பி பொத்தானை அழுத்த முடியவில்லை.',
      back: 'பின்', frameNote: 'உட்பொதிக்கப்பட்ட படிவத்தில்',
    },
    te: {
      ready: 'సిద్ధం', filling: 'నింపబడుతోంది…', done: 'పూర్తయింది', left: '{n} మిగిలింది',
      idleH: 'ఈ దరఖాస్తును స్వయంచాలకంగా నింపండి',
      idleP: '{n} ఫీల్డ్‌లు దొరికాయి. ఇవి మీ Docrud ప్రొఫైల్ నుండి నింపబడతాయి; పంపే ముందు మీరు అన్నీ చూసుకోవచ్చు.',
      fill: 'ఈ దరఖాస్తును నింపండి',
      stepScan: 'ఫారం చదవబడుతోంది', stepMap: 'మీ ప్రొఫైల్‌తో సరిపోల్చుతోంది',
      stepWrite: 'మీ సమాధానాలు రాయబడుతున్నాయి', stepFill: 'ఫారం నింపబడుతోంది',
      confTitle: 'విశ్వాసం', filledOf: '{b}లో {a} ఫీల్డ్‌లు నింపబడ్డాయి',
      subReview: 'పంపే ముందు చూడండి', subFilled: 'నింపబడింది', subLeft: 'మీ కోసం మిగిలింది',
      ctaQuestions: '{n} చిన్న ప్రశ్నలకు సమాధానం ఇవ్వండి', ctaQuestion: '1 చిన్న ప్రశ్నకు సమాధానం ఇవ్వండి',
      ctaSubmit: 'చూసి పంపండి',
      editH: 'ఈ సమాధానాన్ని మార్చండి', save: 'సేవ్', cancel: 'రద్దు', edit: 'మార్చు',
      suggestions: 'సరిపోయే ఇతర సమాధానాలు', looksRight: 'సరిగ్గా ఉంది', checked: 'చూశాను',
      askN: '{n}లో ప్రశ్న {i}', askSrc: 'ఫారం దీన్ని “{x}” అంటుంది',
      askPlaceholder: 'మీ సమాధానం టైప్ చేయండి…', askSend: 'సేవ్ చేసి కొనసాగండి', askSkip: 'దీన్ని వదిలేయండి',
      recall: 'గత సారి మీరు {x} అన్నారు', fromProfile: 'మీ ప్రొఫైల్ నుండి',
      chatMore: 'మరో {n} ఫీల్డ్‌లు నింపబడ్డాయి',
      savedProfile: 'మీ ప్రొఫైల్‌లో సేవ్ అయింది — తదుపరి ఫారంలో ఇది దానంతటే నిండుతుంది.',
      submitH: 'పంపడానికి సిద్ధమా?', submitFix: 'ముందు వీటిని సరిచేయండి',
      submitWarn: 'ఇది సంస్థ యొక్క సొంత సబ్మిట్ బటన్‌ను నొక్కుతుంది. దీన్ని వెనక్కి తీసుకోలేరు.',
      submitGo: 'దరఖాస్తు పంపండి', submitting: 'పంపబడుతోంది…', submitted: 'దరఖాస్తు పంపబడింది',
      errNoFields: 'ఈ పేజీలో ఫారం ఫీల్డ్‌లు లేవు.',
      langLabel: 'భాష', nothingSubmitted: 'మీరు ఇక్కడ సబ్మిట్ నొక్కే వరకు ఏదీ పంపబడదు.',
      reqEmpty: 'తప్పనిసరి, ఇంకా ఖాళీగా ఉంది',
      addProfile: 'మీ Docrud ప్రొఫైల్‌లో {x} జోడిస్తే తదుపరి సారి ఇది దానంతటే నిండుతుంది.',
      youEdited: 'దీన్ని మీరు మార్చారు',
      submitFailed: 'సబ్మిట్ బటన్‌ను నొక్కలేకపోయాం.',
      back: 'వెనక్కి', frameNote: 'ఎంబెడ్ చేసిన ఫారంలో',
    },
    mr: {
      ready: 'तयार', filling: 'भरले जात आहे…', done: 'पूर्ण', left: '{n} शिल्लक',
      idleH: 'हा अर्ज आपोआप भरा',
      idleP: '{n} रकाने सापडले. हे तुमच्या Docrud प्रोफाइलमधून भरले जातील, आणि पाठवण्यापूर्वी तुम्ही सर्व तपासू शकता.',
      fill: 'हा अर्ज भरा',
      stepScan: 'फॉर्म वाचला जात आहे', stepMap: 'तुमच्या प्रोफाइलशी जुळवत आहे',
      stepWrite: 'तुमची उत्तरे लिहिली जात आहेत', stepFill: 'फॉर्म भरला जात आहे',
      confTitle: 'खात्री', filledOf: '{b} पैकी {a} रकाने भरले',
      subReview: 'पाठवण्यापूर्वी तपासा', subFilled: 'भरले', subLeft: 'तुमच्यासाठी शिल्लक',
      ctaQuestions: '{n} छोट्या प्रश्नांची उत्तरे द्या', ctaQuestion: '1 छोट्या प्रश्नाचे उत्तर द्या',
      ctaSubmit: 'तपासा आणि पाठवा',
      editH: 'हे उत्तर बदला', save: 'जतन करा', cancel: 'रद्द करा', edit: 'बदला',
      suggestions: 'जुळणारी इतर उत्तरे', looksRight: 'बरोबर आहे', checked: 'तपासले',
      askN: '{n} पैकी प्रश्न {i}', askSrc: 'फॉर्म याला “{x}” म्हणतो',
      askPlaceholder: 'तुमचे उत्तर लिहा…', askSend: 'जतन करून पुढे जा', askSkip: 'हे वगळा',
      recall: 'मागच्या वेळी तुम्ही {x} म्हणालात', fromProfile: 'तुमच्या प्रोफाइलमधून',
      chatMore: 'आणखी {n} रकाने भरले',
      savedProfile: 'तुमच्या प्रोफाइलमध्ये जतन — पुढच्या फॉर्ममध्ये हे आपोआप भरेल.',
      submitH: 'पाठवण्यास तयार?', submitFix: 'आधी हे दुरुस्त करा',
      submitWarn: 'यामुळे कंपनीचे स्वतःचे सबमिट बटण दाबले जाईल. हे परत घेता येणार नाही.',
      submitGo: 'अर्ज पाठवा', submitting: 'पाठवत आहे…', submitted: 'अर्ज पाठवला',
      errNoFields: 'या पानावर फॉर्मचे रकाने नाहीत.',
      langLabel: 'भाषा', nothingSubmitted: 'तुम्ही येथे सबमिट दाबेपर्यंत काहीही पाठवले जात नाही.',
      reqEmpty: 'आवश्यक, अजून रिकामे',
      addProfile: 'तुमच्या Docrud प्रोफाइलमध्ये {x} जोडा, पुढच्या वेळी हे आपोआप भरेल.',
      youEdited: 'तुम्ही हे बदलले',
      submitFailed: 'सबमिट बटण दाबता आले नाही.',
      back: 'मागे', frameNote: 'एम्बेड केलेल्या फॉर्ममध्ये',
    },
    gu: {
      ready: 'તૈયાર', filling: 'ભરાઈ રહ્યું છે…', done: 'પૂર્ણ', left: '{n} બાકી',
      idleH: 'આ અરજી આપમેળે ભરો',
      idleP: '{n} ખાનાં મળ્યાં. આ તમારી Docrud પ્રોફાઇલમાંથી ભરાશે, અને મોકલતા પહેલાં તમે બધું તપાસી શકો છો.',
      fill: 'આ અરજી ભરો',
      stepScan: 'ફોર્મ વંચાઈ રહ્યું છે', stepMap: 'તમારી પ્રોફાઇલ સાથે મેળવી રહ્યું છે',
      stepWrite: 'તમારા જવાબો લખાઈ રહ્યા છે', stepFill: 'ફોર્મ ભરાઈ રહ્યું છે',
      confTitle: 'ભરોસો', filledOf: '{b} માંથી {a} ખાનાં ભરાયાં',
      subReview: 'મોકલતા પહેલાં તપાસો', subFilled: 'ભરાયું', subLeft: 'તમારા માટે બાકી',
      ctaQuestions: '{n} નાના પ્રશ્નોના જવાબ આપો', ctaQuestion: '1 નાના પ્રશ્નનો જવાબ આપો',
      ctaSubmit: 'તપાસો અને મોકલો',
      editH: 'આ જવાબ બદલો', save: 'સાચવો', cancel: 'રદ કરો', edit: 'બદલો',
      suggestions: 'બંધબેસતા બીજા જવાબો', looksRight: 'બરાબર છે', checked: 'તપાસ્યું',
      askN: '{n} માંથી પ્રશ્ન {i}', askSrc: 'ફોર્મ આને “{x}” કહે છે',
      askPlaceholder: 'તમારો જવાબ લખો…', askSend: 'સાચવીને આગળ વધો', askSkip: 'આ છોડો',
      recall: 'ગયા વખતે તમે {x} કહ્યું હતું', fromProfile: 'તમારી પ્રોફાઇલમાંથી',
      chatMore: 'બીજાં {n} ખાનાં ભરાયાં',
      savedProfile: 'તમારી પ્રોફાઇલમાં સાચવ્યું — આગલા ફોર્મમાં આ જાતે ભરાશે.',
      submitH: 'મોકલવા તૈયાર?', submitFix: 'પહેલાં આ સુધારો',
      submitWarn: 'આનાથી કંપનીનું પોતાનું સબમિટ બટન દબાશે. તે પાછું લઈ શકાતું નથી.',
      submitGo: 'અરજી મોકલો', submitting: 'મોકલાઈ રહ્યું છે…', submitted: 'અરજી મોકલાઈ',
      errNoFields: 'આ પાના પર ફોર્મનાં ખાનાં નથી.',
      langLabel: 'ભાષા', nothingSubmitted: 'તમે અહીં સબમિટ દબાવો નહીં ત્યાં સુધી કશું મોકલાતું નથી.',
      reqEmpty: 'જરૂરી છે, હજી ખાલી છે',
      addProfile: 'તમારી Docrud પ્રોફાઇલમાં {x} ઉમેરો, આગલી વખતે આ જાતે ભરાશે.',
      youEdited: 'તમે આ બદલ્યું',
      submitFailed: 'સબમિટ બટન દબાવી શકાયું નહીં.',
      back: 'પાછા', frameNote: 'એમ્બેડ કરેલા ફોર્મમાં',
    },
    kn: {
      ready: 'ಸಿದ್ಧ', filling: 'ಭರ್ತಿ ಆಗುತ್ತಿದೆ…', done: 'ಮುಗಿದಿದೆ', left: '{n} ಬಾಕಿ',
      idleH: 'ಈ ಅರ್ಜಿಯನ್ನು ತಾನಾಗಿಯೇ ಭರ್ತಿ ಮಾಡಿ',
      idleP: '{n} ಕ್ಷೇತ್ರಗಳು ಸಿಕ್ಕಿವೆ. ಇವು ನಿಮ್ಮ Docrud ಪ್ರೊಫೈಲ್‌ನಿಂದ ಭರ್ತಿಯಾಗುತ್ತವೆ; ಕಳುಹಿಸುವ ಮೊದಲು ನೀವು ಎಲ್ಲವನ್ನೂ ಪರಿಶೀಲಿಸಬಹುದು.',
      fill: 'ಈ ಅರ್ಜಿಯನ್ನು ಭರ್ತಿ ಮಾಡಿ',
      stepScan: 'ಫಾರ್ಮ್ ಓದಲಾಗುತ್ತಿದೆ', stepMap: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ಗೆ ಹೊಂದಿಸಲಾಗುತ್ತಿದೆ',
      stepWrite: 'ನಿಮ್ಮ ಉತ್ತರಗಳನ್ನು ಬರೆಯಲಾಗುತ್ತಿದೆ', stepFill: 'ಫಾರ್ಮ್ ಭರ್ತಿ ಆಗುತ್ತಿದೆ',
      confTitle: 'ವಿಶ್ವಾಸ', filledOf: '{b} ರಲ್ಲಿ {a} ಕ್ಷೇತ್ರಗಳು ಭರ್ತಿ',
      subReview: 'ಕಳುಹಿಸುವ ಮೊದಲು ಪರಿಶೀಲಿಸಿ', subFilled: 'ಭರ್ತಿಯಾಗಿದೆ', subLeft: 'ನಿಮಗಾಗಿ ಬಾಕಿ',
      ctaQuestions: '{n} ಸಣ್ಣ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ', ctaQuestion: '1 ಸಣ್ಣ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರಿಸಿ',
      ctaSubmit: 'ಪರಿಶೀಲಿಸಿ ಕಳುಹಿಸಿ',
      editH: 'ಈ ಉತ್ತರ ಬದಲಿಸಿ', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದು', edit: 'ಬದಲಿಸಿ',
      suggestions: 'ಹೊಂದುವ ಇತರ ಉತ್ತರಗಳು', looksRight: 'ಸರಿಯಾಗಿದೆ', checked: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      askN: '{n} ರಲ್ಲಿ ಪ್ರಶ್ನೆ {i}', askSrc: 'ಫಾರ್ಮ್ ಇದನ್ನು “{x}” ಎನ್ನುತ್ತದೆ',
      askPlaceholder: 'ನಿಮ್ಮ ಉತ್ತರ ಬರೆಯಿರಿ…', askSend: 'ಉಳಿಸಿ ಮುಂದುವರಿಯಿರಿ', askSkip: 'ಇದನ್ನು ಬಿಟ್ಟುಬಿಡಿ',
      recall: 'ಕಳೆದ ಬಾರಿ ನೀವು {x} ಎಂದಿದ್ದೀರಿ', fromProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಿಂದ',
      chatMore: 'ಇನ್ನೂ {n} ಕ್ಷೇತ್ರಗಳು ಭರ್ತಿಯಾದವು',
      savedProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ — ಮುಂದಿನ ಫಾರ್ಮ್‌ನಲ್ಲಿ ಇದು ತಾನಾಗಿಯೇ ಭರ್ತಿಯಾಗುತ್ತದೆ.',
      submitH: 'ಕಳುಹಿಸಲು ಸಿದ್ಧವೇ?', submitFix: 'ಮೊದಲು ಇವನ್ನು ಸರಿಪಡಿಸಿ',
      submitWarn: 'ಇದು ಕಂಪನಿಯ ಸ್ವಂತ ಸಲ್ಲಿಸು ಬಟನ್ ಒತ್ತುತ್ತದೆ. ಇದನ್ನು ಹಿಂಪಡೆಯಲಾಗದು.',
      submitGo: 'ಅರ್ಜಿ ಕಳುಹಿಸಿ', submitting: 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…', submitted: 'ಅರ್ಜಿ ಕಳುಹಿಸಲಾಗಿದೆ',
      errNoFields: 'ಈ ಪುಟದಲ್ಲಿ ಫಾರ್ಮ್ ಕ್ಷೇತ್ರಗಳಿಲ್ಲ.',
      langLabel: 'ಭಾಷೆ', nothingSubmitted: 'ನೀವು ಇಲ್ಲಿ ಸಲ್ಲಿಸು ಒತ್ತುವವರೆಗೆ ಏನೂ ಕಳುಹಿಸುವುದಿಲ್ಲ.',
      reqEmpty: 'ಕಡ್ಡಾಯ, ಇನ್ನೂ ಖಾಲಿ',
      addProfile: 'ನಿಮ್ಮ Docrud ಪ್ರೊಫೈಲ್‌ಗೆ {x} ಸೇರಿಸಿದರೆ ಮುಂದಿನ ಬಾರಿ ಇದು ತಾನಾಗಿಯೇ ಭರ್ತಿಯಾಗುತ್ತದೆ.',
      youEdited: 'ಇದನ್ನು ನೀವು ಬದಲಿಸಿದ್ದೀರಿ',
      submitFailed: 'ಸಲ್ಲಿಸು ಬಟನ್ ಒತ್ತಲಾಗಲಿಲ್ಲ.',
      back: 'ಹಿಂದೆ', frameNote: 'ಎಂಬೆಡ್ ಮಾಡಿದ ಫಾರ್ಮ್‌ನಲ್ಲಿ',
    },
    ml: {
      ready: 'തയ്യാർ', filling: 'പൂരിപ്പിക്കുന്നു…', done: 'പൂർത്തിയായി', left: '{n} ബാക്കി',
      idleH: 'ഈ അപേക്ഷ സ്വയം പൂരിപ്പിക്കുക',
      idleP: '{n} കോളങ്ങൾ കണ്ടെത്തി. ഇവ നിങ്ങളുടെ Docrud പ്രൊഫൈലിൽ നിന്ന് പൂരിപ്പിക്കും; അയയ്ക്കുന്നതിന് മുൻപ് നിങ്ങൾക്ക് എല്ലാം പരിശോധിക്കാം.',
      fill: 'ഈ അപേക്ഷ പൂരിപ്പിക്കുക',
      stepScan: 'ഫോം വായിക്കുന്നു', stepMap: 'നിങ്ങളുടെ പ്രൊഫൈലുമായി ഒത്തുനോക്കുന്നു',
      stepWrite: 'നിങ്ങളുടെ ഉത്തരങ്ങൾ എഴുതുന്നു', stepFill: 'ഫോം പൂരിപ്പിക്കുന്നു',
      confTitle: 'ഉറപ്പ്', filledOf: '{b}ൽ {a} കോളങ്ങൾ പൂരിപ്പിച്ചു',
      subReview: 'അയയ്ക്കും മുൻപ് പരിശോധിക്കുക', subFilled: 'പൂരിപ്പിച്ചു', subLeft: 'നിങ്ങൾക്കായി ബാക്കി',
      ctaQuestions: '{n} ചെറിയ ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുക', ctaQuestion: '1 ചെറിയ ചോദ്യത്തിന് ഉത്തരം നൽകുക',
      ctaSubmit: 'പരിശോധിച്ച് അയയ്ക്കുക',
      editH: 'ഈ ഉത്തരം മാറ്റുക', save: 'സൂക്ഷിക്കുക', cancel: 'റദ്ദാക്കുക', edit: 'മാറ്റുക',
      suggestions: 'ചേരുന്ന മറ്റ് ഉത്തരങ്ങൾ', looksRight: 'ശരിയാണ്', checked: 'പരിശോധിച്ചു',
      askN: '{n}ൽ ചോദ്യം {i}', askSrc: 'ഫോം ഇതിനെ “{x}” എന്ന് വിളിക്കുന്നു',
      askPlaceholder: 'നിങ്ങളുടെ ഉത്തരം എഴുതുക…', askSend: 'സൂക്ഷിച്ച് തുടരുക', askSkip: 'ഇത് ഒഴിവാക്കുക',
      recall: 'കഴിഞ്ഞ തവണ നിങ്ങൾ {x} എന്ന് പറഞ്ഞു', fromProfile: 'നിങ്ങളുടെ പ്രൊഫൈലിൽ നിന്ന്',
      chatMore: 'വേറെ {n} കോളങ്ങൾ പൂരിപ്പിച്ചു',
      savedProfile: 'നിങ്ങളുടെ പ്രൊഫൈലിൽ സൂക്ഷിച്ചു — അടുത്ത ഫോമിൽ ഇത് സ്വയം പൂരിപ്പിക്കും.',
      submitH: 'അയയ്ക്കാൻ തയ്യാറാണോ?', submitFix: 'ആദ്യം ഇവ ശരിയാക്കുക',
      submitWarn: 'ഇത് കമ്പനിയുടെ സ്വന്തം സമർപ്പിക്കൽ ബട്ടൺ അമർത്തും. ഇത് തിരിച്ചെടുക്കാനാവില്ല.',
      submitGo: 'അപേക്ഷ അയയ്ക്കുക', submitting: 'അയയ്ക്കുന്നു…', submitted: 'അപേക്ഷ അയച്ചു',
      errNoFields: 'ഈ പേജിൽ ഫോം കോളങ്ങളില്ല.',
      langLabel: 'ഭാഷ', nothingSubmitted: 'നിങ്ങൾ ഇവിടെ സമർപ്പിക്കുക അമർത്തുന്നതുവരെ ഒന്നും അയയ്ക്കില്ല.',
      reqEmpty: 'നിർബന്ധം, ഇനിയും ഒഴിഞ്ഞുകിടക്കുന്നു',
      addProfile: 'നിങ്ങളുടെ Docrud പ്രൊഫൈലിൽ {x} ചേർത്താൽ അടുത്ത തവണ ഇത് സ്വയം പൂരിപ്പിക്കും.',
      youEdited: 'ഇത് നിങ്ങൾ മാറ്റി',
      submitFailed: 'സമർപ്പിക്കൽ ബട്ടൺ അമർത്താനായില്ല.',
      back: 'പിന്നോട്ട്', frameNote: 'എംബഡ് ചെയ്ത ഫോമിൽ',
    },
    pa: {
      ready: 'ਤਿਆਰ', filling: 'ਭਰਿਆ ਜਾ ਰਿਹਾ ਹੈ…', done: 'ਮੁਕੰਮਲ', left: '{n} ਬਾਕੀ',
      idleH: 'ਇਹ ਅਰਜ਼ੀ ਆਪੇ ਭਰੋ',
      idleP: '{n} ਖਾਨੇ ਮਿਲੇ। ਇਹ ਤੁਹਾਡੀ Docrud ਪ੍ਰੋਫਾਈਲ ਤੋਂ ਭਰੇ ਜਾਣਗੇ, ਅਤੇ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਤੁਸੀਂ ਸਭ ਕੁਝ ਵੇਖ ਸਕਦੇ ਹੋ।',
      fill: 'ਇਹ ਅਰਜ਼ੀ ਭਰੋ',
      stepScan: 'ਫਾਰਮ ਪੜ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ', stepMap: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਨਾਲ ਮੇਲ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ',
      stepWrite: 'ਤੁਹਾਡੇ ਜਵਾਬ ਲਿਖੇ ਜਾ ਰਹੇ ਹਨ', stepFill: 'ਫਾਰਮ ਭਰਿਆ ਜਾ ਰਿਹਾ ਹੈ',
      confTitle: 'ਭਰੋਸਾ', filledOf: '{b} ਵਿੱਚੋਂ {a} ਖਾਨੇ ਭਰੇ',
      subReview: 'ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਵੇਖੋ', subFilled: 'ਭਰੇ ਗਏ', subLeft: 'ਤੁਹਾਡੇ ਲਈ ਬਾਕੀ',
      ctaQuestions: '{n} ਛੋਟੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ', ctaQuestion: '1 ਛੋਟੇ ਸਵਾਲ ਦਾ ਜਵਾਬ ਦਿਓ',
      ctaSubmit: 'ਵੇਖੋ ਅਤੇ ਭੇਜੋ',
      editH: 'ਇਹ ਜਵਾਬ ਬਦਲੋ', save: 'ਸੰਭਾਲੋ', cancel: 'ਰੱਦ ਕਰੋ', edit: 'ਬਦਲੋ',
      suggestions: 'ਢੁਕਵੇਂ ਹੋਰ ਜਵਾਬ', looksRight: 'ਠੀਕ ਹੈ', checked: 'ਵੇਖ ਲਿਆ',
      askN: '{n} ਵਿੱਚੋਂ ਸਵਾਲ {i}', askSrc: 'ਫਾਰਮ ਇਸਨੂੰ “{x}” ਕਹਿੰਦਾ ਹੈ',
      askPlaceholder: 'ਆਪਣਾ ਜਵਾਬ ਲਿਖੋ…', askSend: 'ਸੰਭਾਲ ਕੇ ਅੱਗੇ ਵਧੋ', askSkip: 'ਇਸਨੂੰ ਛੱਡੋ',
      recall: 'ਪਿਛਲੀ ਵਾਰ ਤੁਸੀਂ {x} ਕਿਹਾ ਸੀ', fromProfile: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਤੋਂ',
      chatMore: 'ਹੋਰ {n} ਖਾਨੇ ਭਰੇ ਗਏ',
      savedProfile: 'ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਸੰਭਾਲਿਆ — ਅਗਲੇ ਫਾਰਮ ਵਿੱਚ ਇਹ ਆਪੇ ਭਰ ਜਾਵੇਗਾ।',
      submitH: 'ਭੇਜਣ ਲਈ ਤਿਆਰ?', submitFix: 'ਪਹਿਲਾਂ ਇਹ ਠੀਕ ਕਰੋ',
      submitWarn: 'ਇਸ ਨਾਲ ਕੰਪਨੀ ਦਾ ਆਪਣਾ ਸਬਮਿਟ ਬਟਨ ਦੱਬੇਗਾ। ਇਸਨੂੰ ਵਾਪਸ ਨਹੀਂ ਲਿਆ ਜਾ ਸਕਦਾ।',
      submitGo: 'ਅਰਜ਼ੀ ਭੇਜੋ', submitting: 'ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ…', submitted: 'ਅਰਜ਼ੀ ਭੇਜ ਦਿੱਤੀ',
      errNoFields: 'ਇਸ ਸਫ਼ੇ ਉੱਤੇ ਫਾਰਮ ਦੇ ਖਾਨੇ ਨਹੀਂ ਹਨ।',
      langLabel: 'ਭਾਸ਼ਾ', nothingSubmitted: 'ਜਦ ਤੱਕ ਤੁਸੀਂ ਇੱਥੇ ਸਬਮਿਟ ਨਹੀਂ ਦੱਬਦੇ, ਕੁਝ ਨਹੀਂ ਭੇਜਿਆ ਜਾਂਦਾ।',
      reqEmpty: 'ਲਾਜ਼ਮੀ, ਹਾਲੇ ਖਾਲੀ',
      addProfile: 'ਆਪਣੀ Docrud ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ {x} ਜੋੜੋ, ਅਗਲੀ ਵਾਰ ਇਹ ਆਪੇ ਭਰ ਜਾਵੇਗਾ।',
      youEdited: 'ਤੁਸੀਂ ਇਹ ਬਦਲਿਆ',
      submitFailed: 'ਸਬਮਿਟ ਬਟਨ ਦੱਬਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ।',
      back: 'ਪਿੱਛੇ', frameNote: 'ਇੱਕ ਐਂਬੈਡ ਕੀਤੇ ਫਾਰਮ ਵਿੱਚ',
    },
    es: {
      ready: 'listo', filling: 'rellenando…', done: 'hecho', left: '{n} pendientes',
      idleH: 'Rellenar esta solicitud',
      idleP: 'Se encontraron {n} campos. Se rellenan desde tu perfil de Docrud y tú revisas todo antes de enviar nada.',
      fill: 'Rellenar esta solicitud',
      stepScan: 'Leyendo el formulario', stepMap: 'Comparando con tu perfil',
      stepWrite: 'Escribiendo tus respuestas', stepFill: 'Rellenando el formulario',
      confTitle: 'Confianza', filledOf: '{a} / {b} campos rellenados',
      subReview: 'Revisa antes de enviar', subFilled: 'Rellenado', subLeft: 'Queda para ti',
      ctaQuestions: 'Responde {n} preguntas rápidas', ctaQuestion: 'Responde 1 pregunta rápida',
      ctaSubmit: 'Revisar y enviar',
      editH: 'Editar esta respuesta', save: 'Guardar', cancel: 'Cancelar', edit: 'Editar',
      suggestions: 'Otras respuestas que encajan', looksRight: 'Está bien', checked: 'Revisado',
      askN: 'Pregunta {i} de {n}', askSrc: 'el formulario lo llama «{x}»',
      askPlaceholder: 'Escribe tu respuesta…', askSend: 'Guardar y continuar', askSkip: 'Saltar esta',
      recall: 'La última vez dijiste {x}', fromProfile: 'de tu perfil',
      chatMore: '{n} campos más rellenados',
      savedProfile: 'Guardado en tu perfil: el próximo formulario que lo pida se rellena solo.',
      submitH: '¿Listo para enviar?', submitFix: 'Corrige esto primero',
      submitWarn: 'Esto pulsa el botón de envío del empleador. No se puede deshacer.',
      submitGo: 'Enviar solicitud', submitting: 'Enviando…', submitted: 'Solicitud enviada',
      errNoFields: 'No hay campos de formulario en esta página.',
      langLabel: 'Idioma', nothingSubmitted: 'No se envía nada hasta que pulses enviar aquí.',
      reqEmpty: 'obligatorio, aún vacío',
      addProfile: 'Añade {x} a tu perfil de Docrud y la próxima vez esto se rellena solo.',
      youEdited: 'lo editaste tú',
      submitFailed: 'No se pudo pulsar el botón de envío.',
      back: 'Atrás', frameNote: 'en un formulario incrustado',
    },
    fr: {
      ready: 'prêt', filling: 'remplissage…', done: 'terminé', left: '{n} restantes',
      idleH: 'Remplir cette candidature',
      idleP: '{n} champs trouvés. Ils sont remplis depuis votre profil Docrud, et vous vérifiez tout avant tout envoi.',
      fill: 'Remplir cette candidature',
      stepScan: 'Lecture du formulaire', stepMap: 'Comparaison avec votre profil',
      stepWrite: 'Rédaction de vos réponses', stepFill: 'Remplissage du formulaire',
      confTitle: 'Confiance', filledOf: '{a} / {b} champs remplis',
      subReview: 'À vérifier avant l’envoi', subFilled: 'Rempli', subLeft: 'Laissé pour vous',
      ctaQuestions: 'Répondre à {n} questions rapides', ctaQuestion: 'Répondre à 1 question rapide',
      ctaSubmit: 'Vérifier et envoyer',
      editH: 'Modifier cette réponse', save: 'Enregistrer', cancel: 'Annuler', edit: 'Modifier',
      suggestions: 'Autres réponses possibles', looksRight: 'C’est correct', checked: 'Vérifié',
      askN: 'Question {i} sur {n}', askSrc: 'le formulaire appelle cela « {x} »',
      askPlaceholder: 'Saisissez votre réponse…', askSend: 'Enregistrer et continuer', askSkip: 'Passer',
      recall: 'La dernière fois vous avez répondu {x}', fromProfile: 'depuis votre profil',
      chatMore: '{n} champs de plus remplis',
      savedProfile: 'Enregistré dans votre profil — le prochain formulaire se remplira tout seul.',
      submitH: 'Prêt à envoyer ?', submitFix: 'Corrigez d’abord ceci',
      submitWarn: 'Ceci appuie sur le bouton d’envoi de l’employeur. C’est irréversible.',
      submitGo: 'Envoyer la candidature', submitting: 'Envoi…', submitted: 'Candidature envoyée',
      errNoFields: 'Aucun champ de formulaire sur cette page.',
      langLabel: 'Langue', nothingSubmitted: 'Rien n’est envoyé tant que vous n’appuyez pas ici.',
      reqEmpty: 'obligatoire, encore vide',
      addProfile: 'Ajoutez {x} à votre profil Docrud et la prochaine fois cela se remplira tout seul.',
      youEdited: 'vous l’avez modifié',
      submitFailed: 'Le bouton d’envoi n’a pas pu être actionné.',
      back: 'Retour', frameNote: 'dans un formulaire intégré',
    },
    de: {
      ready: 'bereit', filling: 'wird ausgefüllt…', done: 'fertig', left: 'noch {n}',
      idleH: 'Diese Bewerbung automatisch ausfüllen',
      idleP: '{n} Felder gefunden. Sie werden aus Ihrem Docrud-Profil ausgefüllt, und Sie prüfen alles, bevor etwas gesendet wird.',
      fill: 'Diese Bewerbung ausfüllen',
      stepScan: 'Formular wird gelesen', stepMap: 'Abgleich mit Ihrem Profil',
      stepWrite: 'Ihre Antworten werden geschrieben', stepFill: 'Formular wird ausgefüllt',
      confTitle: 'Sicherheit', filledOf: '{a} / {b} Felder ausgefüllt',
      subReview: 'Vor dem Senden prüfen', subFilled: 'Ausgefüllt', subLeft: 'Für Sie übrig',
      ctaQuestions: '{n} kurze Fragen beantworten', ctaQuestion: '1 kurze Frage beantworten',
      ctaSubmit: 'Prüfen und senden',
      editH: 'Diese Antwort bearbeiten', save: 'Speichern', cancel: 'Abbrechen', edit: 'Bearbeiten',
      suggestions: 'Andere passende Antworten', looksRight: 'Sieht richtig aus', checked: 'Geprüft',
      askN: 'Frage {i} von {n}', askSrc: 'das Formular nennt das „{x}“',
      askPlaceholder: 'Ihre Antwort eingeben…', askSend: 'Speichern und weiter', askSkip: 'Überspringen',
      recall: 'Letztes Mal sagten Sie {x}', fromProfile: 'aus Ihrem Profil',
      chatMore: '{n} weitere Felder ausgefüllt',
      savedProfile: 'In Ihrem Profil gespeichert — das nächste Formular füllt sich von selbst.',
      submitH: 'Bereit zum Senden?', submitFix: 'Bitte zuerst korrigieren',
      submitWarn: 'Dies drückt den Absende-Button des Arbeitgebers. Das lässt sich nicht rückgängig machen.',
      submitGo: 'Bewerbung senden', submitting: 'Wird gesendet…', submitted: 'Bewerbung gesendet',
      errNoFields: 'Keine Formularfelder auf dieser Seite.',
      langLabel: 'Sprache', nothingSubmitted: 'Es wird nichts gesendet, bis Sie hier auf Senden drücken.',
      reqEmpty: 'Pflichtfeld, noch leer',
      addProfile: 'Ergänzen Sie {x} in Ihrem Docrud-Profil, dann füllt sich das beim nächsten Mal von selbst.',
      youEdited: 'von Ihnen bearbeitet',
      submitFailed: 'Der Absende-Button konnte nicht gedrückt werden.',
      back: 'Zurück', frameNote: 'in einem eingebetteten Formular',
    },
  };

  /* ── The questions ───────────────────────────────────────────────────
     Keyed by AnswerKey, which is what a question's signature carries, so the
     translation survives however the employer worded theirs. Only the keys in
     our taxonomy are here; anything else is shown in the employer's own words,
     untranslated and visibly so. */

  const PROMPTS = {
    en: {}, /* the server already sends English */
    hi: {
      workAuthorization: 'क्या आपको इस देश में काम करने की कानूनी अनुमति है?',
      requiresSponsorship: 'क्या आपको कंपनी से वीज़ा स्पॉन्सरशिप चाहिए होगी?',
      willRelocate: 'क्या आप इस नौकरी के लिए दूसरे शहर जा सकते हैं?',
      noticePeriod: 'आप कितनी जल्दी शुरू कर सकते हैं?',
      availableFrom: 'आप किस तारीख से शुरू कर सकते हैं?',
      salaryExpectation: 'आप कितनी सैलरी चाहते हैं?',
      currentSalary: 'अभी आपकी सैलरी कितनी है?',
      yearsExperience: 'आपको कितने साल का अनुभव है?',
      howDidYouHear: 'आपको इस नौकरी के बारे में कहाँ से पता चला?',
      currentTitle: 'अभी आपका पद क्या है?',
      currentCompany: 'अभी आप कहाँ काम करते हैं?',
      phone: 'आपसे संपर्क करने के लिए सबसे अच्छा नंबर कौन सा है?',
      location: 'आप किस शहर में रहते हैं?', city: 'आप किस शहर में रहते हैं?',
      country: 'आप किस देश में हैं?',
      linkedin: 'आपका LinkedIn पता क्या है?', github: 'आपका GitHub पता क्या है?',
      portfolio: 'आपका काम कहाँ देखा जा सकता है?',
      school: 'आपने कहाँ से पढ़ाई की?', degree: 'आपकी डिग्री क्या है?',
      fieldOfStudy: 'आपने क्या पढ़ा?', graduationYear: 'आपने किस साल पूरा किया?',
      coverLetter: 'क्या आप उन्हें कुछ बताना चाहेंगे?',
    },
    bn: {
      workAuthorization: 'এই দেশে কাজ করার আইনি অনুমতি কি আপনার আছে?',
      requiresSponsorship: 'আপনার কি কোম্পানির ভিসা স্পনসরশিপ লাগবে?',
      willRelocate: 'এই কাজের জন্য কি আপনি অন্য শহরে যেতে পারবেন?',
      noticePeriod: 'কত তাড়াতাড়ি শুরু করতে পারবেন?',
      availableFrom: 'কোন তারিখ থেকে শুরু করতে পারবেন?',
      salaryExpectation: 'আপনি কত বেতন চান?',
      currentSalary: 'এখন আপনার বেতন কত?',
      yearsExperience: 'আপনার কত বছরের অভিজ্ঞতা?',
      howDidYouHear: 'এই চাকরির কথা কোথায় শুনেছেন?',
      currentTitle: 'এখন আপনার পদ কী?',
      currentCompany: 'এখন আপনি কোথায় কাজ করেন?',
      phone: 'আপনার সঙ্গে যোগাযোগের সেরা নম্বর কোনটি?',
      location: 'আপনি কোন শহরে থাকেন?', city: 'আপনি কোন শহরে থাকেন?',
      country: 'আপনি কোন দেশে আছেন?',
      linkedin: 'আপনার LinkedIn ঠিকানা কী?', github: 'আপনার GitHub ঠিকানা কী?',
      portfolio: 'আপনার কাজ কোথায় দেখা যাবে?',
      school: 'কোথায় পড়াশোনা করেছেন?', degree: 'আপনার ডিগ্রি কী?',
      fieldOfStudy: 'কী নিয়ে পড়েছেন?', graduationYear: 'কোন বছরে শেষ করেছেন?',
      coverLetter: 'তাদের কিছু বলতে চান?',
    },
    ta: {
      workAuthorization: 'இந்த நாட்டில் வேலை செய்ய உங்களுக்குச் சட்டப்பூர்வ அனுமதி உள்ளதா?',
      requiresSponsorship: 'நிறுவனத்திடமிருந்து விசா ஸ்பான்சர்ஷிப் உங்களுக்குத் தேவைப்படுமா?',
      willRelocate: 'இந்த வேலைக்காக வேறு நகரத்திற்குச் செல்வீர்களா?',
      noticePeriod: 'எவ்வளவு விரைவில் தொடங்க முடியும்?',
      availableFrom: 'எந்தத் தேதியில் தொடங்க முடியும்?',
      salaryExpectation: 'எவ்வளவு சம்பளம் எதிர்பார்க்கிறீர்கள்?',
      currentSalary: 'இப்போது உங்கள் சம்பளம் எவ்வளவு?',
      yearsExperience: 'எத்தனை ஆண்டுகள் அனுபவம்?',
      howDidYouHear: 'இந்த வேலையைப் பற்றி எங்கே கேள்விப்பட்டீர்கள்?',
      currentTitle: 'இப்போது உங்கள் பதவி என்ன?',
      currentCompany: 'இப்போது எங்கே வேலை செய்கிறீர்கள்?',
      phone: 'உங்களைத் தொடர்பு கொள்ள சிறந்த எண் எது?',
      location: 'எந்த நகரத்தில் இருக்கிறீர்கள்?', city: 'எந்த நகரத்தில் இருக்கிறீர்கள்?',
      country: 'எந்த நாட்டில் இருக்கிறீர்கள்?',
      linkedin: 'உங்கள் LinkedIn முகவரி என்ன?', github: 'உங்கள் GitHub முகவரி என்ன?',
      portfolio: 'உங்கள் வேலையை எங்கே பார்க்கலாம்?',
      school: 'எங்கே படித்தீர்கள்?', degree: 'உங்கள் பட்டம் என்ன?',
      fieldOfStudy: 'என்ன படித்தீர்கள்?', graduationYear: 'எந்த ஆண்டு முடித்தீர்கள்?',
      coverLetter: 'அவர்களிடம் ஏதாவது சொல்ல விரும்புகிறீர்களா?',
    },
    te: {
      workAuthorization: 'ఈ దేశంలో పని చేయడానికి మీకు చట్టపరమైన అనుమతి ఉందా?',
      requiresSponsorship: 'మీకు కంపెనీ వీసా స్పాన్సర్‌షిప్ అవసరమా?',
      willRelocate: 'ఈ ఉద్యోగం కోసం వేరే నగరానికి వెళ్తారా?',
      noticePeriod: 'ఎంత త్వరగా మొదలుపెట్టగలరు?',
      availableFrom: 'ఏ తేదీ నుండి మొదలుపెట్టగలరు?',
      salaryExpectation: 'మీరు ఎంత జీతం ఆశిస్తున్నారు?',
      currentSalary: 'ఇప్పుడు మీ జీతం ఎంత?',
      yearsExperience: 'మీకు ఎన్ని సంవత్సరాల అనుభవం?',
      howDidYouHear: 'ఈ ఉద్యోగం గురించి ఎక్కడ విన్నారు?',
      currentTitle: 'ఇప్పుడు మీ హోదా ఏమిటి?',
      currentCompany: 'ఇప్పుడు మీరు ఎక్కడ పని చేస్తున్నారు?',
      phone: 'మిమ్మల్ని సంప్రదించడానికి ఉత్తమ నంబర్ ఏది?',
      location: 'మీరు ఏ నగరంలో ఉన్నారు?', city: 'మీరు ఏ నగరంలో ఉన్నారు?',
      country: 'మీరు ఏ దేశంలో ఉన్నారు?',
      linkedin: 'మీ LinkedIn చిరునామా ఏమిటి?', github: 'మీ GitHub చిరునామా ఏమిటి?',
      portfolio: 'మీ పనిని ఎక్కడ చూడవచ్చు?',
      school: 'మీరు ఎక్కడ చదివారు?', degree: 'మీ డిగ్రీ ఏమిటి?',
      fieldOfStudy: 'మీరు ఏమి చదివారు?', graduationYear: 'ఏ సంవత్సరం పూర్తి చేశారు?',
      coverLetter: 'వారికి ఏమైనా చెప్పాలనుకుంటున్నారా?',
    },
    mr: {
      workAuthorization: 'या देशात काम करण्याची तुम्हाला कायदेशीर परवानगी आहे का?',
      requiresSponsorship: 'तुम्हाला कंपनीकडून व्हिसा स्पॉन्सरशिप लागेल का?',
      willRelocate: 'या नोकरीसाठी तुम्ही दुसऱ्या शहरात जाल का?',
      noticePeriod: 'तुम्ही किती लवकर सुरू करू शकता?',
      availableFrom: 'कोणत्या तारखेपासून सुरू करू शकता?',
      salaryExpectation: 'तुम्हाला किती पगार हवा आहे?',
      currentSalary: 'सध्या तुमचा पगार किती आहे?',
      yearsExperience: 'तुम्हाला किती वर्षांचा अनुभव आहे?',
      howDidYouHear: 'या नोकरीबद्दल तुम्हाला कुठे कळले?',
      currentTitle: 'सध्या तुमचे पद काय आहे?',
      currentCompany: 'सध्या तुम्ही कुठे काम करता?',
      phone: 'तुमच्याशी संपर्क साधण्यासाठी सर्वोत्तम नंबर कोणता?',
      location: 'तुम्ही कोणत्या शहरात राहता?', city: 'तुम्ही कोणत्या शहरात राहता?',
      country: 'तुम्ही कोणत्या देशात आहात?',
      linkedin: 'तुमचा LinkedIn पत्ता काय आहे?', github: 'तुमचा GitHub पत्ता काय आहे?',
      portfolio: 'तुमचे काम कुठे पाहता येईल?',
      school: 'तुम्ही कुठे शिकलात?', degree: 'तुमची पदवी काय आहे?',
      fieldOfStudy: 'तुम्ही काय शिकलात?', graduationYear: 'कोणत्या वर्षी पूर्ण केले?',
      coverLetter: 'तुम्हाला त्यांना काही सांगायचे आहे का?',
    },
    gu: {
      workAuthorization: 'આ દેશમાં કામ કરવાની તમને કાયદેસર પરવાનગી છે?',
      requiresSponsorship: 'તમને કંપની તરફથી વિઝા સ્પોન્સરશિપ જોઈશે?',
      willRelocate: 'આ નોકરી માટે તમે બીજા શહેરમાં જશો?',
      noticePeriod: 'તમે કેટલા જલદી શરૂ કરી શકો?',
      availableFrom: 'કઈ તારીખથી શરૂ કરી શકો?',
      salaryExpectation: 'તમે કેટલો પગાર ઇચ્છો છો?',
      currentSalary: 'અત્યારે તમારો પગાર કેટલો છે?',
      yearsExperience: 'તમને કેટલાં વર્ષનો અનુભવ છે?',
      howDidYouHear: 'આ નોકરી વિશે તમને ક્યાંથી ખબર પડી?',
      currentTitle: 'અત્યારે તમારું પદ શું છે?',
      currentCompany: 'અત્યારે તમે ક્યાં કામ કરો છો?',
      phone: 'તમારો સંપર્ક કરવા માટે શ્રેષ્ઠ નંબર કયો?',
      location: 'તમે કયા શહેરમાં રહો છો?', city: 'તમે કયા શહેરમાં રહો છો?',
      country: 'તમે કયા દેશમાં છો?',
      linkedin: 'તમારું LinkedIn સરનામું શું છે?', github: 'તમારું GitHub સરનામું શું છે?',
      portfolio: 'તમારું કામ ક્યાં જોઈ શકાય?',
      school: 'તમે ક્યાં ભણ્યા?', degree: 'તમારી ડિગ્રી શું છે?',
      fieldOfStudy: 'તમે શું ભણ્યા?', graduationYear: 'કયા વર્ષે પૂરું કર્યું?',
      coverLetter: 'તમે તેમને કંઈ કહેવા માંગો છો?',
    },
    kn: {
      workAuthorization: 'ಈ ದೇಶದಲ್ಲಿ ಕೆಲಸ ಮಾಡಲು ನಿಮಗೆ ಕಾನೂನುಬದ್ಧ ಅನುಮತಿ ಇದೆಯೇ?',
      requiresSponsorship: 'ನಿಮಗೆ ಕಂಪನಿಯಿಂದ ವೀಸಾ ಪ್ರಾಯೋಜಕತ್ವ ಬೇಕಾಗುತ್ತದೆಯೇ?',
      willRelocate: 'ಈ ಕೆಲಸಕ್ಕಾಗಿ ಬೇರೆ ಊರಿಗೆ ಹೋಗುತ್ತೀರಾ?',
      noticePeriod: 'ಎಷ್ಟು ಬೇಗ ಆರಂಭಿಸಬಹುದು?',
      availableFrom: 'ಯಾವ ದಿನಾಂಕದಿಂದ ಆರಂಭಿಸಬಹುದು?',
      salaryExpectation: 'ನೀವು ಎಷ್ಟು ಸಂಬಳ ನಿರೀಕ್ಷಿಸುತ್ತೀರಿ?',
      currentSalary: 'ಈಗ ನಿಮ್ಮ ಸಂಬಳ ಎಷ್ಟು?',
      yearsExperience: 'ನಿಮಗೆ ಎಷ್ಟು ವರ್ಷಗಳ ಅನುಭವ?',
      howDidYouHear: 'ಈ ಕೆಲಸದ ಬಗ್ಗೆ ಎಲ್ಲಿ ಕೇಳಿದಿರಿ?',
      currentTitle: 'ಈಗ ನಿಮ್ಮ ಹುದ್ದೆ ಏನು?',
      currentCompany: 'ಈಗ ನೀವು ಎಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತೀರಿ?',
      phone: 'ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಲು ಉತ್ತಮ ಸಂಖ್ಯೆ ಯಾವುದು?',
      location: 'ನೀವು ಯಾವ ಊರಿನಲ್ಲಿದ್ದೀರಿ?', city: 'ನೀವು ಯಾವ ಊರಿನಲ್ಲಿದ್ದೀರಿ?',
      country: 'ನೀವು ಯಾವ ದೇಶದಲ್ಲಿದ್ದೀರಿ?',
      linkedin: 'ನಿಮ್ಮ LinkedIn ವಿಳಾಸ ಏನು?', github: 'ನಿಮ್ಮ GitHub ವಿಳಾಸ ಏನು?',
      portfolio: 'ನಿಮ್ಮ ಕೆಲಸವನ್ನು ಎಲ್ಲಿ ನೋಡಬಹುದು?',
      school: 'ನೀವು ಎಲ್ಲಿ ಓದಿದಿರಿ?', degree: 'ನಿಮ್ಮ ಪದವಿ ಏನು?',
      fieldOfStudy: 'ನೀವು ಏನು ಓದಿದಿರಿ?', graduationYear: 'ಯಾವ ವರ್ಷ ಮುಗಿಸಿದಿರಿ?',
      coverLetter: 'ಅವರಿಗೆ ಏನಾದರೂ ಹೇಳಲು ಬಯಸುತ್ತೀರಾ?',
    },
    ml: {
      workAuthorization: 'ഈ രാജ്യത്ത് ജോലി ചെയ്യാൻ നിങ്ങൾക്ക് നിയമപരമായ അനുമതിയുണ്ടോ?',
      requiresSponsorship: 'നിങ്ങൾക്ക് കമ്പനിയുടെ വിസ സ്പോൺസർഷിപ്പ് വേണ്ടിവരുമോ?',
      willRelocate: 'ഈ ജോലിക്കായി മറ്റൊരു നഗരത്തിലേക്ക് മാറുമോ?',
      noticePeriod: 'എത്ര വേഗം തുടങ്ങാൻ കഴിയും?',
      availableFrom: 'ഏത് തീയതി മുതൽ തുടങ്ങാം?',
      salaryExpectation: 'നിങ്ങൾ എത്ര ശമ്പളം പ്രതീക്ഷിക്കുന്നു?',
      currentSalary: 'ഇപ്പോൾ നിങ്ങളുടെ ശമ്പളം എത്രയാണ്?',
      yearsExperience: 'നിങ്ങൾക്ക് എത്ര വർഷത്തെ പരിചയമുണ്ട്?',
      howDidYouHear: 'ഈ ജോലിയെക്കുറിച്ച് എവിടെ നിന്ന് അറിഞ്ഞു?',
      currentTitle: 'ഇപ്പോൾ നിങ്ങളുടെ തസ്തിക എന്താണ്?',
      currentCompany: 'ഇപ്പോൾ എവിടെ ജോലി ചെയ്യുന്നു?',
      phone: 'നിങ്ങളെ ബന്ധപ്പെടാൻ ഏറ്റവും നല്ല നമ്പർ ഏതാണ്?',
      location: 'നിങ്ങൾ ഏത് നഗരത്തിലാണ്?', city: 'നിങ്ങൾ ഏത് നഗരത്തിലാണ്?',
      country: 'നിങ്ങൾ ഏത് രാജ്യത്താണ്?',
      linkedin: 'നിങ്ങളുടെ LinkedIn വിലാസം എന്താണ്?', github: 'നിങ്ങളുടെ GitHub വിലാസം എന്താണ്?',
      portfolio: 'നിങ്ങളുടെ ജോലി എവിടെ കാണാം?',
      school: 'എവിടെ പഠിച്ചു?', degree: 'നിങ്ങളുടെ ബിരുദം എന്താണ്?',
      fieldOfStudy: 'എന്ത് പഠിച്ചു?', graduationYear: 'ഏത് വർഷം പൂർത്തിയാക്കി?',
      coverLetter: 'അവരോട് എന്തെങ്കിലും പറയാനുണ്ടോ?',
    },
    pa: {
      workAuthorization: 'ਕੀ ਤੁਹਾਨੂੰ ਇਸ ਦੇਸ਼ ਵਿੱਚ ਕੰਮ ਕਰਨ ਦੀ ਕਾਨੂੰਨੀ ਇਜਾਜ਼ਤ ਹੈ?',
      requiresSponsorship: 'ਕੀ ਤੁਹਾਨੂੰ ਕੰਪਨੀ ਤੋਂ ਵੀਜ਼ਾ ਸਪਾਂਸਰਸ਼ਿਪ ਚਾਹੀਦੀ ਹੋਵੇਗੀ?',
      willRelocate: 'ਕੀ ਤੁਸੀਂ ਇਸ ਨੌਕਰੀ ਲਈ ਦੂਜੇ ਸ਼ਹਿਰ ਜਾਓਗੇ?',
      noticePeriod: 'ਤੁਸੀਂ ਕਿੰਨੀ ਜਲਦੀ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ?',
      availableFrom: 'ਕਿਸ ਤਾਰੀਖ ਤੋਂ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ?',
      salaryExpectation: 'ਤੁਸੀਂ ਕਿੰਨੀ ਤਨਖਾਹ ਚਾਹੁੰਦੇ ਹੋ?',
      currentSalary: 'ਹੁਣ ਤੁਹਾਡੀ ਤਨਖਾਹ ਕਿੰਨੀ ਹੈ?',
      yearsExperience: 'ਤੁਹਾਡੇ ਕੋਲ ਕਿੰਨੇ ਸਾਲ ਦਾ ਤਜਰਬਾ ਹੈ?',
      howDidYouHear: 'ਇਸ ਨੌਕਰੀ ਬਾਰੇ ਤੁਹਾਨੂੰ ਕਿੱਥੋਂ ਪਤਾ ਲੱਗਾ?',
      currentTitle: 'ਹੁਣ ਤੁਹਾਡਾ ਅਹੁਦਾ ਕੀ ਹੈ?',
      currentCompany: 'ਹੁਣ ਤੁਸੀਂ ਕਿੱਥੇ ਕੰਮ ਕਰਦੇ ਹੋ?',
      phone: 'ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਨ ਲਈ ਸਭ ਤੋਂ ਵਧੀਆ ਨੰਬਰ ਕਿਹੜਾ ਹੈ?',
      location: 'ਤੁਸੀਂ ਕਿਸ ਸ਼ਹਿਰ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?', city: 'ਤੁਸੀਂ ਕਿਸ ਸ਼ਹਿਰ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?',
      country: 'ਤੁਸੀਂ ਕਿਸ ਦੇਸ਼ ਵਿੱਚ ਹੋ?',
      linkedin: 'ਤੁਹਾਡਾ LinkedIn ਪਤਾ ਕੀ ਹੈ?', github: 'ਤੁਹਾਡਾ GitHub ਪਤਾ ਕੀ ਹੈ?',
      portfolio: 'ਤੁਹਾਡਾ ਕੰਮ ਕਿੱਥੇ ਵੇਖਿਆ ਜਾ ਸਕਦਾ ਹੈ?',
      school: 'ਤੁਸੀਂ ਕਿੱਥੋਂ ਪੜ੍ਹਾਈ ਕੀਤੀ?', degree: 'ਤੁਹਾਡੀ ਡਿਗਰੀ ਕੀ ਹੈ?',
      fieldOfStudy: 'ਤੁਸੀਂ ਕੀ ਪੜ੍ਹਿਆ?', graduationYear: 'ਕਿਸ ਸਾਲ ਪੂਰਾ ਕੀਤਾ?',
      coverLetter: 'ਕੀ ਤੁਸੀਂ ਉਨ੍ਹਾਂ ਨੂੰ ਕੁਝ ਦੱਸਣਾ ਚਾਹੋਗੇ?',
    },
    es: {
      workAuthorization: '¿Tienes permiso legal para trabajar en el país de este puesto?',
      requiresSponsorship: '¿Necesitarías que la empresa te patrocine un visado?',
      willRelocate: '¿Te mudarías a otra ciudad por este puesto?',
      noticePeriod: '¿Cuándo podrías empezar?',
      availableFrom: '¿Desde qué fecha podrías empezar?',
      salaryExpectation: '¿Qué salario buscas?',
      currentSalary: '¿Cuánto ganas ahora?',
      yearsExperience: '¿Cuántos años llevas trabajando?',
      howDidYouHear: '¿Dónde te enteraste de este puesto?',
      currentTitle: '¿Cuál es tu puesto actual?',
      currentCompany: '¿Dónde trabajas ahora?',
      phone: '¿Cuál es el mejor número para contactarte?',
      location: '¿En qué ciudad estás?', city: '¿En qué ciudad estás?',
      country: '¿En qué país estás?',
      linkedin: '¿Cuál es tu dirección de LinkedIn?', github: '¿Cuál es tu dirección de GitHub?',
      portfolio: '¿Dónde pueden ver tu trabajo?',
      school: '¿Dónde estudiaste?', degree: '¿Qué titulación tienes?',
      fieldOfStudy: '¿Qué estudiaste?', graduationYear: '¿En qué año terminaste?',
      coverLetter: '¿Quieres contarles algo?',
    },
    fr: {
      workAuthorization: 'Avez-vous le droit de travailler légalement dans le pays de ce poste ?',
      requiresSponsorship: 'Auriez-vous besoin que l’entreprise parraine un visa ?',
      willRelocate: 'Déménageriez-vous dans une autre ville pour ce poste ?',
      noticePeriod: 'Dans combien de temps pourriez-vous commencer ?',
      availableFrom: 'À partir de quelle date pourriez-vous commencer ?',
      salaryExpectation: 'Quel salaire recherchez-vous ?',
      currentSalary: 'Combien gagnez-vous actuellement ?',
      yearsExperience: 'Depuis combien d’années travaillez-vous ?',
      howDidYouHear: 'Où avez-vous entendu parler de ce poste ?',
      currentTitle: 'Quel est votre poste actuel ?',
      currentCompany: 'Où travaillez-vous actuellement ?',
      phone: 'Quel est le meilleur numéro pour vous joindre ?',
      location: 'Dans quelle ville êtes-vous ?', city: 'Dans quelle ville êtes-vous ?',
      country: 'Dans quel pays êtes-vous ?',
      linkedin: 'Quelle est votre adresse LinkedIn ?', github: 'Quelle est votre adresse GitHub ?',
      portfolio: 'Où peut-on voir votre travail ?',
      school: 'Où avez-vous étudié ?', degree: 'Quel diplôme avez-vous ?',
      fieldOfStudy: 'Qu’avez-vous étudié ?', graduationYear: 'En quelle année avez-vous terminé ?',
      coverLetter: 'Souhaitez-vous leur dire quelque chose ?',
    },
    de: {
      workAuthorization: 'Dürfen Sie in dem Land dieser Stelle legal arbeiten?',
      requiresSponsorship: 'Bräuchten Sie ein vom Unternehmen gesponsertes Visum?',
      willRelocate: 'Würden Sie für diese Stelle in eine andere Stadt ziehen?',
      noticePeriod: 'Wie schnell könnten Sie anfangen?',
      availableFrom: 'Ab welchem Datum könnten Sie anfangen?',
      salaryExpectation: 'Welches Gehalt stellen Sie sich vor?',
      currentSalary: 'Was verdienen Sie derzeit?',
      yearsExperience: 'Wie viele Jahre arbeiten Sie schon?',
      howDidYouHear: 'Wo haben Sie von dieser Stelle erfahren?',
      currentTitle: 'Was ist Ihre aktuelle Position?',
      currentCompany: 'Wo arbeiten Sie derzeit?',
      phone: 'Unter welcher Nummer erreicht man Sie am besten?',
      location: 'In welcher Stadt sind Sie?', city: 'In welcher Stadt sind Sie?',
      country: 'In welchem Land sind Sie?',
      linkedin: 'Wie lautet Ihre LinkedIn-Adresse?', github: 'Wie lautet Ihre GitHub-Adresse?',
      portfolio: 'Wo kann man Ihre Arbeit sehen?',
      school: 'Wo haben Sie studiert?', degree: 'Welchen Abschluss haben Sie?',
      fieldOfStudy: 'Was haben Sie studiert?', graduationYear: 'In welchem Jahr haben Sie abgeschlossen?',
      coverLetter: 'Möchten Sie ihnen etwas mitteilen?',
    },
  };

  /** Shown in the picker, in the language's own script — a person looking for
      their language should not have to know its English name. */
  const LANGUAGES = [
    ['en', 'English'], ['hi', 'हिन्दी'], ['bn', 'বাংলা'], ['ta', 'தமிழ்'],
    ['te', 'తెలుగు'], ['mr', 'मराठी'], ['gu', 'ગુજરાતી'], ['kn', 'ಕನ್ನಡ'],
    ['ml', 'മലയാളം'], ['pa', 'ਪੰਜਾਬੀ'], ['es', 'Español'], ['fr', 'Français'],
    ['de', 'Deutsch'],
  ];

  let current = 'en';

  function setLang(code) {
    current = UI[code] ? code : 'en';
    return current;
  }
  function lang() { return current; }

  /** A string, with {placeholders} filled. Falls back to English, then to the
      key itself — a missing translation should degrade to readable English,
      never to a blank button. */
  function t(key, vars) {
    const s = (UI[current] && UI[current][key]) || UI.en[key] || key;
    if (!vars) return s;
    return s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] == null ? m : String(vars[k])));
  }

  /**
   * Our wording for a question, in the chosen language.
   *
   * Only for signatures of the form `key:<AnswerKey>`. Anything else is the
   * employer's own question and is returned unchanged — translating it would
   * be putting words in their mouth about, frequently, someone's legal status.
   */
  function prompt(signature, englishPrompt) {
    if (current === 'en' || !signature || !signature.startsWith('key:')) return englishPrompt;
    const table = PROMPTS[current];
    return (table && table[signature.slice(4)]) || englishPrompt;
  }

  /** The browser's language, if we speak it. The starting point before the
      person has chosen, because most people never open a language menu. */
  function detect() {
    const tags = (navigator.languages && navigator.languages.length
      ? navigator.languages : [navigator.language || 'en']);
    for (const tag of tags) {
      const base = String(tag).toLowerCase().split('-')[0];
      if (UI[base]) return base;
    }
    return 'en';
  }

  const api = { t, prompt, setLang, lang, detect, LANGUAGES };
  if (typeof globalThis !== 'undefined') globalThis.DocrudLang = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();
