/**
 * Server-side client for the EXTERNAL job scraper.
 *
 * The scraper is a separate project. DoCrud never runs it from the browser and
 * never accepts a raw URL to fetch — the admin selects an ALLOWLISTED source
 * name (config registry) and the server maps it to the scraper. Two modes:
 *
 *   JOB_SCRAPER_MODE=service  (production)  → HTTP to a dedicated scraper service
 *   JOB_SCRAPER_MODE=local    (dev only)    → execFile the local scraper CLI
 *
 * The scraper only ever returns the 13 CSV content columns; every system field
 * (id, status, source, createdBy…) is still generated by the EXISTING importer
 * (lib/server/job-import.ts). Secrets (service URL/key, filesystem paths) live
 * only here on the server and are never returned to the client.
 */

export type ScraperMode = 'service' | 'local' | 'unconfigured';

export interface ScraperStatus {
  mode: ScraperMode;
  configured: boolean;
  sources: string[];   // allowlisted source NAMES only — no URLs, no secrets
}

export interface ScrapeResult {
  runId: string;
  status: string;
  scanned: number;
  valid: number;
  invalid: number;
  duplicates: number;
  csv: string;         // 13-column CSV — public job content only
}

const SOURCE_RE = /^[a-z0-9][a-z0-9._-]{0,63}$/i;

export function getScraperMode(): ScraperMode {
  const m = (process.env.JOB_SCRAPER_MODE || '').trim().toLowerCase();
  return m === 'service' || m === 'local' ? m : 'unconfigured';
}

/** Allowlisted source names from env (comma-separated). SSRF-safe registry. */
export function getAllowedSources(): string[] {
  return (process.env.JOB_SCRAPER_SOURCES || '')
    .split(',')
    .map((s) => s.trim())
    .filter((s) => SOURCE_RE.test(s));
}

export function getScraperStatus(): ScraperStatus {
  const mode = getScraperMode();
  const sources = getAllowedSources();
  let configured = false;
  if (mode === 'service') {
    configured = Boolean(process.env.JOB_SCRAPER_URL) && sources.length > 0;
  } else if (mode === 'local') {
    // Local execution is a development convenience only — never in production.
    configured = process.env.NODE_ENV !== 'production' && Boolean(process.env.JOB_SCRAPER_DIR) && sources.length > 0;
  }
  return { mode, configured, sources };
}

function clampLimit(raw: unknown): number {
  const n = Math.floor(Number(raw) || 0);
  return Math.max(1, Math.min(1000, n || 50));
}

/** Run a scrape for an ALLOWLISTED source. Throws with a safe message on error. */
export async function runScraper(opts: { source: string; limit?: number; resume?: boolean }): Promise<ScrapeResult> {
  const mode = getScraperMode();
  const allowed = getAllowedSources();
  const source = String(opts.source || '').trim();

  if (mode === 'unconfigured') throw new Error('Job scraper is not configured.');
  if (!SOURCE_RE.test(source) || !allowed.includes(source)) {
    // Never fetch an arbitrary/unknown source — only the configured allowlist.
    throw new Error('Unknown or disallowed scraper source.');
  }
  const limit = clampLimit(opts.limit);
  const resume = Boolean(opts.resume);

  if (mode === 'service') return runViaService(source, limit, resume);

  // local
  if (process.env.NODE_ENV === 'production') {
    throw new Error('Local scraper mode is disabled in production.');
  }
  return runViaLocal(source, limit, resume);
}

// --------------------------------------------------------------------------- //
// Service mode (production)
// --------------------------------------------------------------------------- //
async function runViaService(source: string, limit: number, resume: boolean): Promise<ScrapeResult> {
  const base = (process.env.JOB_SCRAPER_URL || '').replace(/\/+$/, '');
  if (!base) throw new Error('Job scraper service URL is not configured.');
  const key = process.env.JOB_SCRAPER_API_KEY || '';

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 120_000);
  try {
    const res = await fetch(`${base}/scrape`, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        ...(key ? { authorization: `Bearer ${key}` } : {}),
      },
      body: JSON.stringify({ source, limit, resume }),
      signal: controller.signal,
    });
    if (!res.ok) throw new Error(`Scraper service returned ${res.status}.`);
    const data = (await res.json()) as Partial<ScrapeResult>;
    return normalizeResult(data);
  } catch (err) {
    // Never surface internal URLs/keys.
    throw new Error(err instanceof Error && err.name === 'AbortError' ? 'Scraper service timed out.' : 'Scraper service request failed.');
  } finally {
    clearTimeout(timer);
  }
}

// --------------------------------------------------------------------------- //
// Local mode (development only) — execFile the CLI with FIXED args, no shell.
// --------------------------------------------------------------------------- //
async function runViaLocal(source: string, limit: number, resume: boolean): Promise<ScrapeResult> {
  const { execFile } = await import('child_process');
  const { promisify } = await import('util');
  const { mkdtemp, readFile, rm } = await import('fs/promises');
  const os = await import('os');
  const path = await import('path');
  const run = promisify(execFile);

  const dir = process.env.JOB_SCRAPER_DIR || '';
  if (!dir) throw new Error('Local scraper directory is not configured.');
  const python = process.env.JOB_SCRAPER_PYTHON || path.join(dir, '.venv', 'bin', 'python');

  const tmp = await mkdtemp(path.join(os.tmpdir(), 'scrape-'));
  const outCsv = path.join(tmp, 'jobs.csv');
  const stateDb = path.join(tmp, 'state.sqlite');
  // Fixed, non-shell argument vector. `source` is allowlisted + regex-checked;
  // `limit` is a clamped integer. No user string is interpolated into a shell.
  const args = ['scrape.py', '--source', source, '--limit', String(limit), '--out', outCsv, '--state', stateDb];
  if (resume) args.push('--resume');

  try {
    const { stdout } = await run(python, args, {
      cwd: dir,
      timeout: 120_000,
      maxBuffer: 32 * 1024 * 1024,
      env: { ...process.env },
    });
    const csv = await readFile(outCsv, 'utf8').catch(() => '');
    const counts = parseSummary(stdout || '');
    return {
      runId: `local-${Date.now()}`,
      status: 'completed',
      csv,
      ...counts,
    };
  } catch {
    // Do not leak filesystem paths or stderr to the client.
    throw new Error('Local scraper run failed. Check the server logs.');
  } finally {
    await rm(tmp, { recursive: true, force: true }).catch(() => {});
  }
}

// The CLI prints: "scanned=4 written=2 invalid=1 duplicates=1 skipped_visited=0 no_job_extracted=0"
function parseSummary(stdout: string): { scanned: number; valid: number; invalid: number; duplicates: number } {
  const num = (key: string) => {
    const m = stdout.match(new RegExp(`${key}=(\\d+)`));
    return m ? Number(m[1]) : 0;
  };
  return {
    scanned: num('scanned'),
    valid: num('written'),      // "written" == jobs that passed the scraper's own validation
    invalid: num('invalid'),
    duplicates: num('duplicates'),
  };
}

function normalizeResult(data: Partial<ScrapeResult>): ScrapeResult {
  const int = (v: unknown) => (Number.isFinite(Number(v)) ? Math.max(0, Math.floor(Number(v))) : 0);
  const csv = typeof data.csv === 'string' ? data.csv : '';
  if (!csv.trim()) throw new Error('Scraper returned no CSV.');
  return {
    runId: String(data.runId || `run-${Date.now()}`),
    status: String(data.status || 'completed'),
    scanned: int(data.scanned),
    valid: int(data.valid),
    invalid: int(data.invalid),
    duplicates: int(data.duplicates),
    csv,
  };
}
