/**
 * Internal (in-DoCrud) job scraper — shared types.
 *
 * The scraper produces ONLY the 13 CSV content columns. Every system field
 * (id, status, source, createdBy…, timestamps) is generated by the EXISTING
 * importer (lib/server/job-import.ts). No new job model, no second pipeline.
 */

export type SourceProvider =
  | 'ashby' | 'lever' | 'greenhouse'
  /* Stage 3 — all public, unauthenticated board endpoints. */
  | 'workday' | 'smartrecruiters' | 'workable' | 'recruitee' | 'personio' | 'bamboohr'
  | 'jsonld';

export interface ScrapeSource {
  /** Stable identifier the admin selects (never a raw URL). */
  name: string;
  label?: string;
  enabled: boolean;
  /** Which fetch/parse strategy this source uses. Defaults to 'jsonld'. */
  provider?: SourceProvider;
  /** Provider board/company identifier (Ashby board / Lever company / Greenhouse board). */
  board?: string;
  /**
   * Workday only. Its public URL is
   * https://{tenant}.{shard}.myworkdayjobs.com/wday/cxs/{tenant}/{site}/jobs
   * so a single slug cannot address a board — all three parts are required,
   * and forcing Workday into the slug model would just produce broken URLs.
   */
  workday?: { tenant: string; shard: string; site: string };
  /** Optional country tag for the source registry (e.g. 'IN'). Presentation only. */
  country?: string;
  /** SSRF guard: the ONLY host the fetcher is allowed to request for this source. */
  host: string;
  /** Discovery: a sitemap of job pages (preferred) or a listing page to crawl. */
  sitemapUrl?: string;
  listingUrl?: string;
  /** CSS-ish selector for job-detail links on the listing page. */
  jobLinkSelector?: string;
  /** CSS fallback selectors, used only when a page has no JobPosting JSON-LD. */
  cssFallback?: Partial<Record<
    'title' | 'organizationName' | 'location' | 'department' | 'description' |
    'responsibilities' | 'requirements' | 'preferredSkills' | 'applyUrl',
    string
  >>;
  /** Bounded crawl controls (serverless-safe). */
  maxPages?: number;
  minIntervalMs?: number;
}

export interface RawJob {
  sourceUrl: string;
  title: string;
  organizationName: string;
  location: string;
  department: string;
  employmentType: string;
  workMode: string;
  experienceLevel: string;
  description: string;               // may be HTML
  responsibilities: string[];
  requirements: string[];
  preferredSkills: string[];
  targetRoleKeywords: string[];
  applyUrl: string;
}

export interface ScrapeResult {
  runId: string;
  status: string;
  scanned: number;      // pages fetched
  valid: number;        // rows extracted with the required content
  invalid: number;      // pages that yielded no usable JobPosting
  duplicates: number;   // within-batch duplicates removed (existing-job dedup is the importer's job)
  csv: string;          // 13-column CSV — public content only
}

/** Injectable dependencies so the pipeline is testable without network. */
export interface ScrapeDeps {
  /** Fetch a URL's text (already robots/host-checked by the caller). */
  fetchText?: (url: string) => Promise<{ status: number; text: string } | null>;
  /** Whether robots.txt allows fetching this URL. */
  robotsAllows?: (url: string) => Promise<boolean>;
  /** Deterministic time source (tests); defaults to Date.now. */
  now?: () => number;
}

/**
 * A job normalized from any provider into a common shape, before it is turned
 * into the 13 CSV content columns the existing importer accepts. Only real
 * fields are populated — missing data stays empty (never invented).
 */
export interface NormalizedJob {
  source: string;          // source name, e.g. 'ashby:acme'
  provider: SourceProvider;
  externalId: string;      // provider job id (dedup identity: provider+externalId)
  title: string;
  organizationName: string;
  location: string;
  department: string;
  employmentType: string;  // canonical (full_time…) or ''
  workMode: string;        // remote | hybrid | onsite | ''
  experienceLevel: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  preferredSkills: string[];
  targetRoleKeywords: string[];
  salaryPresent: boolean;
  postedAt: string;        // ISO or ''
  jobUrl: string;
  applyUrl: string;
  isActive: boolean;       // listed/published (only true is importable)
  score?: number;
}

/** Injectable deps for provider fetching (tests inject fixtures — no network). */
export interface ProviderDeps {
  fetchJson?: (url: string) => Promise<unknown | null>;
  /** Workday's board endpoint is a POST. Injected so tests need no network. */
  fetchJsonPost?: (url: string, body: unknown) => Promise<unknown | null>;
  /** Personio's XML feed, and any fetch that must not follow redirects. */
  fetchTextStrict?: (url: string) => Promise<{ status: number; text: string } | null>;
  now?: () => number;
}

export interface SourceRunStat {
  name: string;
  provider: SourceProvider;
  fetched: number;
  active: number;
  failed: boolean;
  error?: string;
}

export interface AggregateScrapeResult {
  sources: number;
  fetched: number;
  valid: number;
  duplicates: number;   // within-batch duplicates removed before import
  imported: number;
  rejected: number;
  failed: number;       // sources that errored
  perSource: SourceRunStat[];
  csv: string;
  runAt: string;
}
