/**
 * Internal (in-DoCrud) job scraper — shared types.
 *
 * The scraper produces ONLY the 13 CSV content columns. Every system field
 * (id, status, source, createdBy…, timestamps) is generated by the EXISTING
 * importer (lib/server/job-import.ts). No new job model, no second pipeline.
 */

export interface ScrapeSource {
  /** Stable identifier the admin selects (never a raw URL). */
  name: string;
  label?: string;
  enabled: boolean;
  /** SSRF guard: the ONLY host the fetcher is allowed to request for this source. */
  host: string;
  /** Discovery: a sitemap of job pages (preferred) or a listing page to crawl. */
  sitemapUrl?: string;
  listingUrl?: string;
  /** CSS-ish selector for job-detail links on the listing page. */
  jobLinkSelector?: string;
  /** CSS fallback selectors, used only when a page has no JobPosting JSON-LD. */
  cssFallback?: Partial<Record<
    'title' | 'organizationName' | 'location' | 'department' | 'description' |
    'responsibilities' | 'requirements' | 'preferredSkills' | 'applyUrl',
    string
  >>;
  /** Bounded crawl controls (serverless-safe). */
  maxPages?: number;
  minIntervalMs?: number;
}

export interface RawJob {
  sourceUrl: string;
  title: string;
  organizationName: string;
  location: string;
  department: string;
  employmentType: string;
  workMode: string;
  experienceLevel: string;
  description: string;               // may be HTML
  responsibilities: string[];
  requirements: string[];
  preferredSkills: string[];
  targetRoleKeywords: string[];
  applyUrl: string;
}

export interface ScrapeResult {
  runId: string;
  status: string;
  scanned: number;      // pages fetched
  valid: number;        // rows extracted with the required content
  invalid: number;      // pages that yielded no usable JobPosting
  duplicates: number;   // within-batch duplicates removed (existing-job dedup is the importer's job)
  csv: string;          // 13-column CSV — public content only
}

/** Injectable dependencies so the pipeline is testable without network. */
export interface ScrapeDeps {
  /** Fetch a URL's text (already robots/host-checked by the caller). */
  fetchText?: (url: string) => Promise<{ status: number; text: string } | null>;
  /** Whether robots.txt allows fetching this URL. */
  robotsAllows?: (url: string) => Promise<boolean>;
  /** Deterministic time source (tests); defaults to Date.now. */
  now?: () => number;
}
